### PR TITLE
Upgrade static-module fix security bug

### PR DESCRIPTION
**Pull request by arj03**
I'm creating a PR to urify to get that fixes as well

### CODE REVIEW

**Comment by arj03** [comment]
Also tests doesn't appear to run because of standard?

**Comment by arj03** [comment]
I fixed the tests by removing the standard test and got urify fixed upstream so bumped that as well.

**Comment by ahdinosaur** [comment]
oops hella late to the party, fixed the code for standard style, then cherry-picked the commits from here, and published as 1.0.2, cheers @arj03! :tada:

**Comment by arj03** [comment]
Better late than never. Thanks @ahdinosaur :)

**Pull request closed without merging**
