### PR TITLE
fix: space paths

### LINKED ISSUE #3: Require-style breaks when directory contains spaces
# How to reproduce

Install patchbay under a directory path that includes spaces, e.g. '/Users/tim/Large Files/src/patchbay/'

# Symptoms (in patchbay)

FontAwesome is not loaded in patchbay so Filter icons are rendered as plain squares.

# Details

The main body of the css file starts: 

`@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.7.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'),` 

Using the console you can see that urls are not enclosed in single quotes  

`>>requireStyle('font-awesome').substring(212,400)`

`"@font-face {
  font-family: 'FontAwesome';
  src: url(/Users/tim/Large Files/src/patchbay/node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0);
  src: url(/Users/tim/Large File"`

An earlier version of patchbay used fs.readFileSync() which works. For comparison the console output is below 

`>>readFileSync(fontCssPath, 'utf8')
  .replace(/\.{2}/g, (match) => join(dirname(fontCssPath), match)).substring(212,400)`

`"@font-face {
  font-family: 'FontAwesome';
  src: url('/Users/tim/Large Files/src/patchbay/node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0');
  src: url('/Users/tim/Large F"`

# Workaround

Don't install patchbay under a directory path that includes spaces :)

### PR DESCRIPTION
**Pull request by ahdinosaur**
fixes https://github.com/ahdinosaur/require-style/issues/3

/cc @mixmix, hey would it be possible for you to test whether this works in Patchbay?

### CODE REVIEW

**Comment by mixmix** [comment]
hey @ahdinosaur this breaks with this linked in in patchbay : 

```js
requireStyle('highlight.js/styles/github.css')
```

---

```
base.html:19 Error: Cannot find module 'highlight.js/styles/github.css' from '/home/mix/projects/require-style/node_modules/style-resolve'
    at Function.module.exports [as sync] (/home/mix/projects/require-style/node_modules/resolve/lib/sync.js:69)
    at Function.resolveSync [as sync] (/home/mix/projects/require-style/node_modules/style-resolve/index.js:22)
    at requireStyle (/home/mix/projects/require-style/index.js:13)
    at nest (/home/mix/projects/SSBC/patchbay/app/styles/css/highlight.js:9)
    at /home/mix/projects/SSBC/patchbay/node_modules/depject/apply.js:9
    at Array.reduce (<anonymous>)
    at Object.css (/home/mix/projects/SSBC/patchbay/node_modules/depject/apply.js:8)
    at Object.styles (/home/mix/projects/SSBC/patchbay/app/sync/initialise/styles.js:17)
    at Object.initialise (/home/mix/projects/SSBC/patchbay/node_modules/depject/apply.js:18)
    at Object.start (/home/mix/projects/SSBC/patchbay/app/sync/start.js:25)
    at Object.start (/home/mix/projects/SSBC/patchbay/node_modules/depject/apply.js:18)
    at Start (/home/mix/projects/SSBC/patchbay/ui.js:23)
    at <anonymous>:9:35
    at WebFrame.(anonymous function) [as executeJavaScript] (/home/mix/projects/SSBC/patchbay/node_modules/electron/dist/resources/electron.asar/renderer/api/web-frame.js:56:27)
    at resolve (/home/mix/projects/SSBC/patchbay/node_modules/electron/dist/resources/electron.asar/renderer/web-frame-init.js:15)
    at new Promise (<anonymous>)
```

BUT it works fine with font-awesome I think (ssb-ahoy works fine, which uses require-style)

**Comment by ahdinosaur** [comment]
i think that's because `style-resolve` is trying to resolve from within the symlinked `require-style` directory and not finding the module.

i ran Patchbay locally after:

```
npm i --save ahdinosaur/require-style#fix/space-paths
```

and it seems to work, but keen to confirm with you before i merge and publish (and i'm too lazy to write proper tests :sweat_smile: )

**Comment by ahdinosaur** [comment]
although now i fixed that, so it should work whether with `npm link` or `npm install`, i'm glad you stumbled on that error as now the module resolving should be more correct.

**Comment by mixmix** [comment]
now that you mention it I noticed it didn't play well with other modules that were symlinked ... (recently added a new font to patchbay via modules)... ok so is this good to merge? I think you've answered the question yourself and this is working? (I've not tried it but trust what you describe, and also know that if something goes weird with e.g. windows installs that there was this change)

**Comment by ahdinosaur** [comment]
sweet, published as `require-style@1.1.0` :tada:

**Pull request merged**
